[package]
name = "el-driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
el-ast = { path = "../el-ast", version = "=0.1.0" }
el-codegen = { path = "../el-codegen", version = "=0.1.0" }
el-ir = { path = "../el-ir", version = "=0.1.0" }
el-parser = { path = "../el-parser", version = "=0.1.0" }
el-resolve = { path = "../el-resolve", version = "=0.1.0" }
el-span = { path = "../el-span", version = "=0.1.0" }
el-types = { path = "../el-types", version = "=0.1.0" }

[features]
default = []
llvm = ["el-codegen/llvm"]
managed-runtime = ["llvm", "el-codegen/managed-runtime"]
gc-stress-test = ["managed-runtime", "el-codegen/gc-stress-test"]
allocation-failure-test = ["managed-runtime", "el-codegen/allocation-failure-test"]

[[example]]
name = "compile_source"
required-features = ["llvm"]

[lints]
workspace = true
