[workspace]
members = [
    "crates/el-ast",
    "crates/el-cli",
    "crates/el-driver",
    "crates/el-parser",
    "crates/el-runtime",
    "crates/el-span",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
pest = "=2.8.7"
pest_derive = "=2.8.7"
