[package]
name = "el-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
el-ast = { path = "../el-ast", version = "=0.1.0" }
el-span = { path = "../el-span", version = "=0.1.0" }
pest.workspace = true
pest_derive.workspace = true

[lints]
workspace = true
