[package]
name = "el-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
el-resolve = { path = "../el-resolve", version = "=0.1.0" }
el-span = { path = "../el-span", version = "=0.1.0" }
el-types = { path = "../el-types", version = "=0.1.0" }

[dev-dependencies]
el-parser = { path = "../el-parser", version = "=0.1.0" }

[lints]
workspace = true
